In [19]:
#Import All Libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#Import the dataset
df=pd.read_csv("heart_disease_data.csv")

#Data Preprocessing
scalar=StandardScaler()
X=df.drop("target",axis=1)
y=df["target"]
x=pd.DataFrame(scalar.fit_transform(X),columns=X.columns)

#Train-Test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

#Model's Accuracy
models=[]
models.append(('Logistic Regression',LogisticRegression(max_iter=1000)))
models.append(('KNN',KNeighborsClassifier()))
models.append(('RandomForestClassifier',RandomForestClassifier()))
models.append(('SVM',SVC(kernel='linear')))
models.append(('Naive Bayes',GaussianNB()))
for name,model in models:
    print()
    print("****",name,"*****")
    print()
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print("Accuracy Score:",accuracy_score(y_pred,y_test))

**** Logistic Regression *****

Accuracy Score: 0.8064516129032258

**** KNN *****

Accuracy Score: 0.8709677419354839

**** RandomForestClassifier *****

Accuracy Score: 0.8064516129032258

**** SVM *****

Accuracy Score: 0.8387096774193549

**** Naive Bayes *****

Accuracy Score: 0.8387096774193549

In [21]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1