In [47]:
#Import All The Libraries
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

df1=pd.read_csv("calories.csv")
df2=pd.read_csv("exercise.csv")
df=pd.concat([df2,df1['Calories']],axis=1)
df['Gender']=df['Gender'].map({"male":1,"female":0})

scalar=StandardScaler()
X=df.drop('Calories',axis=1)
x=pd.DataFrame(scalar.fit_transform(X),columns=X.columns)
y=df['Calories']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Model Training and Accuracy Check
models=[]
models.append(('XGBRegressor',XGBRegressor()))
models.append(('Linear Regression', LinearRegression()))
models.append(('Random Forest Regressor',RandomForestRegressor()))
for name,model in models:
    print("\n")
    print("*******************Model Name : ",name,"*********************")
    print()
    model.fit(x_train,y_train)
    x_pred=model.predict(x_test)
    print("Accuracy :",r2_score(y_test,x_pred))

*******************Model Name :  XGBRegressor *********************

Accuracy : 0.9987901041693489


*******************Model Name :  Linear Regression *********************

Accuracy : 0.9672759152492366


*******************Model Name :  Random Forest Regressor *********************

Accuracy : 0.9980002240835959

In [39]:
df.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,1,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,0,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,1,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,0,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,0,27,154.0,58.0,10.0,81.0,39.8,35.0