In [11]:
#Import All The Libraries
import numpy as np
import pandas as pd
import seaborn  as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

#Import The Dataset
df=pd.read_csv("winequality-red.csv")

#Data Cleaning
def Mean_value(df,column):
    mean_value=df[column].mean()
    df.fillna({column:mean_value},inplace=True)
num_cols=[col for col in df.columns if df[col].dtype=="float64"]
for col in num_cols:
    Mean_value(df,col)

#Data Preprocessing
scalar=StandardScaler()
X=df.drop("quality",axis=1)
y=df["quality"].apply(lambda y_value:1 if y_value>=7 else 0)
x=pd.DataFrame(scalar.fit_transform(X),columns=X.columns)

#Train-Test Splitting
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print("X-Train Shape:",x_train.shape)
print("X-Test Shape :",x_test.shape)
print("Y_train shape:",y_train.shape)
print("Y_Test Shape :",y_test.shape)

#Model Training and Accuracy Check
models=[]
models.append(('Logistic Regression',LogisticRegression(max_iter=1000)))
models.append(('KNN',KNeighborsClassifier()))
models.append(('RandomForestClassifier',RandomForestClassifier()))
models.append(('SVM',SVC(kernel='linear')))
for name,model in models:
    print("\n")
    print("*******************Model Name : ",name,"*********************")
    print()
    model.fit(x_train,y_train)
    x_pred=model.predict(x_test)
    print("Accuracy :",accuracy_score(y_test,x_pred))

X-Train Shape: (1199, 11)
X-Test Shape : (400, 11)
Y_train shape: (1199,)
Y_Test Shape : (400,)


*******************Model Name :  Logistic Regression *********************

Accuracy : 0.8775


*******************Model Name :  KNN *********************

Accuracy : 0.895


*******************Model Name :  RandomForestClassifier *********************

Accuracy : 0.91


*******************Model Name :  SVM *********************

Accuracy : 0.8675

In [5]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [15]:
def Mean_value(df,column):
    mean_value=df[column].mean()
    df.fillna({column:mean_value},inplace=True)
num_cols=[col for col in df.columns if df[col].dtype=="float64"]
for col in num_cols:
    Mean_value(df,col)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5